### ISSUE TITLE
Doesn't seem to respect respect the nodeselector

### ISSUE THREAD

**Issue by dvdvorle** [decayofmind/kube-better-node#1]
In my case I have Linux and (labelled) Windows nodes, with a nodeselector on the pod, but `kube-better-node` seems to think the Linux nodes are viable targets for my Windows pods. So it keeps evicting those pods. Would be nice if it would also check de nodeselector and `requiredDuringSchedulingIgnoredDuringExecution` affinities.

**Comment by decayofmind** [comment]
Hi @dvdvorle I'm not sure if you still using the tool, but the problem you've mentioned here is fixed in v0.0.1 with #3
